/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.projetobiblioteca;

/**
 *
 * @author userale
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private AddLivro dados = new AddLivro();
    /** 
     * Creates new form POHADATELAPRINCIPAL
     */
    public TelaInicial() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBerro = new javax.swing.JButton();
        JLtitulo = new javax.swing.JLabel();
        JBaluguel = new javax.swing.JButton();
        JBcompra = new javax.swing.JButton();
        JBcadastrar = new javax.swing.JButton();
        JBclientes = new javax.swing.JButton();
        JBcadastrarLivro = new javax.swing.JButton();

        JBerro.setText("ERRO");
        JBerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBerroActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLtitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        JLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        JBaluguel.setText("ALUGAR");
        JBaluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBaluguelActionPerformed(evt);
            }
        });

        JBcompra.setText("COMPRAR");
        JBcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcompraActionPerformed(evt);
            }
        });

        JBcadastrar.setText("Cadastro de cliente");
        JBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcadastrarActionPerformed(evt);
            }
        });

        JBclientes.setText("Clientes já cadastrados");
        JBclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBclientesActionPerformed(evt);
            }
        });

        JBcadastrarLivro.setText("Cadastrar um livro");
        JBcadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcadastrarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 395, Short.MAX_VALUE)
                        .addComponent(JLtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBcadastrar)
                            .addComponent(JBclientes))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JBcompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBcadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JBaluguel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(JLtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBcadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBclientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBcadastrarLivro)
                .addGap(17, 17, 17)
                .addComponent(JBaluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBaluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBaluguelActionPerformed
        TelaAlugarLivro dialogAl = new TelaAlugarLivro( this ,this.dados);
        
        dialogAl.setVisible(true);
        
    }//GEN-LAST:event_JBaluguelActionPerformed

    private void JBcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcompraActionPerformed
        TelaVendaLivro dialogComp = new TelaVendaLivro(this , this.dados);
        
        dialogComp.setVisible(true);   
        
    }//GEN-LAST:event_JBcompraActionPerformed

    private void JBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcadastrarActionPerformed
        TelaCadastrarClientes dialogCadastro = new TelaCadastrarClientes(this,this.dados);
        
        dialogCadastro.setVisible(true);
        

    }//GEN-LAST:event_JBcadastrarActionPerformed

    private void JBerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBerroActionPerformed
           TelaNada dialogErro = new TelaNada(this,true);
           
           dialogErro.setVisible(true);
           
    }//GEN-LAST:event_JBerroActionPerformed

    private void JBclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBclientesActionPerformed
           TelaClientes dialogClientes = new TelaClientes(this, this.dados);
           
           dialogClientes.setVisible(true);
           
    }//GEN-LAST:event_JBclientesActionPerformed

    private void JBcadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcadastrarLivroActionPerformed
       TelaCadastrarLivros dialogCadastroLivros = new TelaCadastrarLivros(this,this. dados);
       
       dialogCadastroLivros.setVisible(true);
       
    }//GEN-LAST:event_JBcadastrarLivroActionPerformed

  
    public static void main(String args[]) {
      

        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new TelaInicial().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBaluguel;
    private javax.swing.JButton JBcadastrar;
    private javax.swing.JButton JBcadastrarLivro;
    private javax.swing.JButton JBclientes;
    private javax.swing.JButton JBcompra;
    private javax.swing.JButton JBerro;
    private javax.swing.JLabel JLtitulo;
    // End of variables declaration//GEN-END:variables
}
